<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BhavaniTech.Core\BhavaniTech.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app_logo.jpg" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app_logo.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
